name: Deploy push to master

on:
  push:
    branches:
      - master

jobs:
  check:
    name: Check
    uses: ./.github/workflows/_check.yaml
    secrets: inherit
  build:
    name: Build
    needs: check
    uses: ./.github/workflows/_docker.yaml
    secrets: inherit
  # deploy:
  #   name: Deploy
  #   needs: build
  #   uses: ./.github/workflows/_kube.yaml
  #   secrets: inherit
